services:
  - type: web
    name: exam_app_server
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: 0
      - key: DATABASE_URL
        fromDatabase:
          name: exam-db
          property: connectionString

databases:
  - name: exam-db
    plan: free
