services:
  - type: web
    name: exam-app-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: 0