"""user name changes unique true to false

Revision ID: 1413b6d7a394
Revises: 40c51711841d
Create Date: 2025-09-10 16:41:14.133018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1413b6d7a394'
down_revision = '40c51711841d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
