"""table column changes

Revision ID: 6d2325e595b9
Revises: b4b8f08b19b9
Create Date: 2025-09-16 14:08:44.493370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2325e595b9'
down_revision = 'b4b8f08b19b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinee_attempt_exam_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negative_marking_value', sa.Float(), nullable=True))
        batch_op.create_unique_constraint(None, ['attempt_result_id'])

    with op.batch_alter_table('examinee_attempt_questions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['attempt_question_id'])

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['exam_id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['question_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('examinee_attempt_questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('examinee_attempt_exam_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('negative_marking_value')

    # ### end Alembic commands ###
