"""deleted exams and created again

Revision ID: 6d5be967dd38
Revises: bcd6f0f64036
Create Date: 2025-09-11 22:32:24.395642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5be967dd38'
down_revision = 'bcd6f0f64036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('exam_name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.String(length=100), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('attempts_allowed', sa.String(length=20), nullable=True),
    sa.Column('negative_marks_value', sa.Float(), nullable=True),
    sa.Column('examiner_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_image_url', sa.Text(), nullable=True),
    sa.Column('question_image_id', sa.String(length=255), nullable=True),
    sa.Column('optA_text', sa.Text(), nullable=False),
    sa.Column('optA_image_url', sa.Text(), nullable=True),
    sa.Column('optA_image_id', sa.String(length=255), nullable=True),
    sa.Column('optB_text', sa.Text(), nullable=False),
    sa.Column('optB_image_url', sa.Text(), nullable=True),
    sa.Column('optB_image_id', sa.String(length=255), nullable=True),
    sa.Column('optC_text', sa.Text(), nullable=False),
    sa.Column('optC_image_url', sa.Text(), nullable=True),
    sa.Column('optC_image_id', sa.String(length=255), nullable=True),
    sa.Column('optD_text', sa.Text(), nullable=False),
    sa.Column('optD_image_url', sa.Text(), nullable=True),
    sa.Column('optD_image_id', sa.String(length=255), nullable=True),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('question_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('questions')
    op.drop_table('exams')
    # ### end Alembic commands ###
