"""created

Revision ID: 7c36a8fe5526
Revises: 
Create Date: 2025-09-19 16:22:36.117486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c36a8fe5526'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('exams',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('exam_name', sa.String(length=255), nullable=False),
    sa.Column('exam_code', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.String(length=100), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('attempts_allowed', sa.String(length=20), nullable=True),
    sa.Column('negative_marks_value', sa.Float(), nullable=True),
    sa.Column('examiner_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id'),
    sa.UniqueConstraint('exam_code'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('examinee_attempt_exams',
    sa.Column('attempt_exam_id', sa.UUID(), nullable=False),
    sa.Column('examinee_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('unanswered_questions', sa.Integer(), nullable=False),
    sa.Column('time_taken_minutes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examinee_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_exam_id'),
    sa.UniqueConstraint('attempt_exam_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_image_url', sa.Text(), nullable=True),
    sa.Column('question_image_id', sa.String(length=255), nullable=True),
    sa.Column('optA_text', sa.Text(), nullable=False),
    sa.Column('optA_image_url', sa.Text(), nullable=True),
    sa.Column('optA_image_id', sa.String(length=255), nullable=True),
    sa.Column('optB_text', sa.Text(), nullable=False),
    sa.Column('optB_image_url', sa.Text(), nullable=True),
    sa.Column('optB_image_id', sa.String(length=255), nullable=True),
    sa.Column('optC_text', sa.Text(), nullable=False),
    sa.Column('optC_image_url', sa.Text(), nullable=True),
    sa.Column('optC_image_id', sa.String(length=255), nullable=True),
    sa.Column('optD_text', sa.Text(), nullable=False),
    sa.Column('optD_image_url', sa.Text(), nullable=True),
    sa.Column('optD_image_id', sa.String(length=255), nullable=True),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('examinee_attempt_exam_questions',
    sa.Column('attempt_question_id', sa.UUID(), nullable=False),
    sa.Column('attempt_exam_id', sa.UUID(), nullable=False),
    sa.Column('original_question_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_image_url', sa.Text(), nullable=True),
    sa.Column('question_image_id', sa.String(length=255), nullable=True),
    sa.Column('option_a_text', sa.Text(), nullable=True),
    sa.Column('option_a_image_url', sa.Text(), nullable=True),
    sa.Column('option_a_image_id', sa.String(length=255), nullable=True),
    sa.Column('option_b_text', sa.Text(), nullable=True),
    sa.Column('option_b_image_url', sa.Text(), nullable=True),
    sa.Column('option_b_image_id', sa.String(length=255), nullable=True),
    sa.Column('option_c_text', sa.Text(), nullable=True),
    sa.Column('option_c_image_url', sa.Text(), nullable=True),
    sa.Column('option_c_image_id', sa.String(length=255), nullable=True),
    sa.Column('option_d_text', sa.Text(), nullable=True),
    sa.Column('option_d_image_url', sa.Text(), nullable=True),
    sa.Column('option_d_image_id', sa.String(length=255), nullable=True),
    sa.Column('correct_option_label', sa.String(length=5), nullable=False),
    sa.Column('selected_option_label', sa.String(length=5), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_exam_id'], ['examinee_attempt_exams.attempt_exam_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_question_id'], ['questions.question_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('attempt_question_id'),
    sa.UniqueConstraint('attempt_question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examinee_attempt_exam_questions')
    op.drop_table('questions')
    op.drop_table('examinee_attempt_exams')
    op.drop_table('exams')
    op.drop_table('users')
    # ### end Alembic commands ###
