"""Initial migrate

Revision ID: bcd6f0f64036
Revises: 
Create Date: 2025-09-11 19:24:03.088849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd6f0f64036'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('exams',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('exam_name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.String(length=100), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('attempts_allowed', sa.String(length=20), nullable=True),
    sa.Column('negative_marks_value', sa.Float(), nullable=True),
    sa.Column('examiner_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_image_url', sa.Text(), nullable=True),
    sa.Column('question_image_id', sa.String(length=255), nullable=True),
    sa.Column('optA_text', sa.Text(), nullable=False),
    sa.Column('optA_image_url', sa.Text(), nullable=True),
    sa.Column('optA_image_id', sa.String(length=255), nullable=True),
    sa.Column('optB_text', sa.Text(), nullable=False),
    sa.Column('optB_image_url', sa.Text(), nullable=True),
    sa.Column('optB_image_id', sa.String(length=255), nullable=True),
    sa.Column('optC_text', sa.Text(), nullable=False),
    sa.Column('optC_image_url', sa.Text(), nullable=True),
    sa.Column('optC_image_id', sa.String(length=255), nullable=True),
    sa.Column('optD_text', sa.Text(), nullable=False),
    sa.Column('optD_image_url', sa.Text(), nullable=True),
    sa.Column('optD_image_id', sa.String(length=255), nullable=True),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('exams')
    op.drop_table('users')
    # ### end Alembic commands ###
